---
title: "CA Club Survey 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(magrittr)
library(ggplot2)
library(janitor)
library(plotly)
library(DT)

source("run.R")
```

# General
## Respondents by Federation


```{r by-federation, echo = FALSE, warning = FALSE}
DT::datatable(df_clean %>% 
                count(Federation) %>% 
                adorn_totals)
```


## Club ownership

# Club membership
Histogram of club memberships
```{r total member histogram, echo=FALSE}
g_total_membership %>% ggplotly()
```

# Total membership types by Federation

```{r, echo = FALSE}
DT::datatable(tbl_membership_by_fed)
```

# GC only clubs

```{r, echo = FALSE}
DT::datatable(tbl_GC_only_by_fed)
```

# GC and AC by Federation

```{r, echo = FALSE}
DT::datatable(tbl_GC_vs_AC_by_fed)
```

# Taking up AC

```{r, echo = FALSE}
DT::datatable(tbl_taking_up_ac)
```

# Feedback
```{r, echo = FALSE}
DT::datatable(df_what_can_ca_do_better)
```

```{r, echo = FALSE}
DT::datatable(df_feedback_for_ca)
```





